import { leaguesService } from '../leagues.service.js';
import type { LeagueInput } from '../leagues.types.js';

const defaultLeagues: LeagueInput[] = [
  {
    externalId: 'standard-5x5-roto-auction',
    name: 'Standard 5x5 Roto (Auction)',
    description: 'Traditional 5x5 rotisserie scoring with auction draft',
    format: 'roto',
    draftType: 'auction',
    battingCategories: ['R', 'HR', 'RBI', 'SB', 'AVG'],
    pitchingCategories: ['W', 'SV', 'K', 'ERA', 'WHIP'],
    rosterSlots: {
      C: 2,
      '1B': 1,
      '2B': 1,
      '3B': 1,
      SS: 1,
      CI: 0,
      MI: 0,
      OF: 5,
      DH: 0,
      SP: 9,
      RP: 4,
      P: 0,
      UTIL: 0,
      BENCH: 0,
    },
    totalBudget: 260,
    isDefault: true,
  },
  {
    externalId: 'standard-5x5-roto-snake',
    name: 'Standard 5x5 Roto (Snake)',
    description: 'Traditional 5x5 rotisserie scoring with snake draft',
    format: 'roto',
    draftType: 'snake',
    battingCategories: ['R', 'HR', 'RBI', 'SB', 'AVG'],
    pitchingCategories: ['W', 'SV', 'K', 'ERA', 'WHIP'],
    rosterSlots: {
      C: 2,
      '1B': 1,
      '2B': 1,
      '3B': 1,
      SS: 1,
      CI: 0,
      MI: 0,
      OF: 5,
      DH: 0,
      SP: 9,
      RP: 4,
      P: 0,
      UTIL: 0,
      BENCH: 0,
    },
    isDefault: true,
  },
  {
    externalId: 'obp-league-auction',
    name: 'OBP League (Auction)',
    description: '5x5 league using OBP instead of AVG',
    format: 'roto',
    draftType: 'auction',
    battingCategories: ['R', 'HR', 'RBI', 'SB', 'OBP'],
    pitchingCategories: ['W', 'SV', 'K', 'ERA', 'WHIP'],
    rosterSlots: {
      C: 2,
      '1B': 1,
      '2B': 1,
      '3B': 1,
      SS: 1,
      CI: 0,
      MI: 0,
      OF: 5,
      DH: 0,
      SP: 9,
      RP: 4,
      P: 0,
      UTIL: 0,
      BENCH: 0,
    },
    totalBudget: 260,
    isDefault: true,
  },
  {
    externalId: 'deep-league-auction',
    name: 'Deep League (Auction)',
    description: 'Deeper roster slots with bench and utility positions',
    format: 'roto',
    draftType: 'auction',
    battingCategories: ['R', 'HR', 'RBI', 'SB', 'AVG'],
    pitchingCategories: ['W', 'SV', 'K', 'ERA', 'WHIP'],
    rosterSlots: {
      C: 2,
      '1B': 1,
      '2B': 1,
      '3B': 1,
      SS: 1,
      CI: 0,
      MI: 0,
      OF: 5,
      DH: 1,
      SP: 9,
      RP: 4,
      P: 0,
      UTIL: 2,
      BENCH: 5,
    },
    totalBudget: 260,
    isDefault: true,
  },
  {
    externalId: '6x6-roto-qs-auction',
    name: '6x6 Roto with QS (Auction)',
    description: 'Expanded categories including OPS and Quality Starts',
    format: 'roto',
    draftType: 'auction',
    battingCategories: ['R', 'HR', 'RBI', 'SB', 'AVG', 'OPS'],
    pitchingCategories: ['QS', 'SV', 'K', 'ERA', 'WHIP', 'K'],
    rosterSlots: {
      C: 2,
      '1B': 1,
      '2B': 1,
      '3B': 1,
      SS: 1,
      CI: 0,
      MI: 0,
      OF: 5,
      DH: 0,
      SP: 9,
      RP: 4,
      P: 0,
      UTIL: 0,
      BENCH: 0,
    },
    totalBudget: 260,
    isDefault: true,
  },
  {
    externalId: 'saves-holds-league-auction',
    name: 'Saves+Holds League (Auction)',
    description: 'Values all relief pitchers with SV+HLD category',
    format: 'roto',
    draftType: 'auction',
    battingCategories: ['R', 'HR', 'RBI', 'SB', 'AVG'],
    pitchingCategories: ['W', 'SV+HLD', 'K', 'ERA', 'WHIP'],
    rosterSlots: {
      C: 2,
      '1B': 1,
      '2B': 1,
      '3B': 1,
      SS: 1,
      CI: 0,
      MI: 0,
      OF: 5,
      DH: 0,
      SP: 7,
      RP: 6,
      P: 0,
      UTIL: 0,
      BENCH: 0,
    },
    totalBudget: 260,
    isDefault: true,
  },
];

export async function seedDefaultLeagues(): Promise<void> {
  try {
    console.log('Seeding default leagues...');
    const count = await leaguesService.upsertLeagues(defaultLeagues);
    console.log(`✓ Seeded ${count} default leagues`);
  } catch (error) {
    console.error('Failed to seed default leagues:', error);
    // Don't throw - server should still start even if seeding fails
  }
}
